
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Jun 19 14:47:49 CEST 2019
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 33;
  public static final int CONST = 8;
  public static final int RET = 13;
  public static final int GRT = 26;
  public static final int NUMCONST = 45;
  public static final int NOTEQUAL = 25;
  public static final int LPAREN = 42;
  public static final int SEMI = 35;
  public static final int CONTINUE = 17;
  public static final int INTERFACE = 5;
  public static final int FOR = 15;
  public static final int MINUS = 20;
  public static final int RPAREN = 43;
  public static final int AND = 30;
  public static final int OR = 31;
  public static final int COMMA = 36;
  public static final int CLASS = 4;
  public static final int EQUALEQUAL = 24;
  public static final int DIV = 22;
  public static final int PLUS = 19;
  public static final int IF = 9;
  public static final int DOT = 37;
  public static final int LESEQUAL = 29;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 34;
  public static final int EQUAL = 32;
  public static final int NEW = 10;
  public static final int error = 1;
  public static final int MUL = 21;
  public static final int PERCENT = 23;
  public static final int IDENT = 44;
  public static final int BREAK = 3;
  public static final int VOID = 14;
  public static final int GRTEQUAL = 27;
  public static final int LBRACE = 38;
  public static final int ELSE = 7;
  public static final int LSQUARE = 40;
  public static final int ENUM = 6;
  public static final int READ = 12;
  public static final int CHARCONST = 46;
  public static final int RSQUARE = 41;
  public static final int RBRACE = 39;
  public static final int LES = 28;
  public static final int BOOLCONST = 47;
  public static final int EXTENDS = 16;
  public static final int PROG = 2;
  public static final int IMPLEMENTS = 18;
  public static final int PRINT = 11;
}

